/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AssurixsEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "AssurixsNextjs": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "AssurixsPostgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "AssurixsUploads": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AssurixsVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "EmailApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}